### ISSUE TITLE
Support for LSP?

### ISSUE THREAD

**Issue by mamcx** [zesterer/ariadne#1]
I wonder how could this be integrated into [LSP](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol), to forward the diagnostics to the editor(s). 

P.D: Comming from https://www.reddit.com/r/rust/comments/okza9q/i_just_released_ariadne_a_crate_for_generating/h5bqd1j

**Comment by zesterer** [comment]
I think the first place to look is rustc's JSON output: https://doc.rust-lang.org/rustc/json.html

However, I think that LSP support is broadly tangential to the aims of the crate and should be implemented instead by a dedicated per-language server.
