### ISSUE TITLE
Upgrade to `yansi 1.0`

### ISSUE THREAD

**Issue by mohammadfawaz** [zesterer/ariadne#106]
The [`yansi`](https://crates.io/crates/yansi) crate is now at `1.0`. It's probably worth upgrading `ariadne` to use `yansi v1.0` for two reasons:
1. `yansi 1.0` is hopefully more stable.
2. Projects using `ariadne` that want to upgrade to `yansi 1.0` will have an easier time if `ariadne` also uses `yansi 1.0`.

**Comment by zesterer** [comment]
Yep, this is definitely something to be done. I'll try to find time over the next week or so.
