### ISSUE TITLE
Use line numbers instead of character position

### ISSUE THREAD

**Issue by ryangjchandler** [zesterer/ariadne#20]
Is it possible to render errors based on line number and then the column? My parser resets the column position on each new line, so rendering errors is difficult since an error on the 4th line at column 4..5 is being rendered as the 4th and 5th characters in the entire source.

**Comment by zesterer** [comment]
This is not currently possible, but I might be able to build this feature into the API refactor I'm working on.

**Comment by ryangjchandler** [comment]
Yeah that would be awesome.

**Comment by kaplanelad** [comment]
Hey @zesterer, any update regarding this issue?

**Comment by zesterer** [comment]
I think this should be possible with the `offset` method on `Source`: https://docs.rs/ariadne/latest/ariadne/struct.Line.html#method.offset.
