### ISSUE TITLE
Error labels don't line up with error location

### ISSUE THREAD

**Issue by geom3trik** [zesterer/ariadne#23]
I tried running the multiline example and the label does not line up with the error. Here is an image to show what I mean:
![image](https://user-images.githubusercontent.com/9365407/146015668-fa24555c-b0a1-4bbf-866d-26b9d15810e0.png)

**Comment by zesterer** [comment]
Oh goodness, this sounds like #19. Does this work on `master`, or not?

**Comment by geom3trik** [comment]
Hi, I'm not sure what you mean, I don't see any other branches other than `main` so that's the one I tried running the example on.

**Comment by geom3trik** [comment]
> Oh goodness, this sounds like #19. 

Okay so I just tried replacing the new lines from CRLF to LF and that seems to have fixed it. So this appears to be a duplicate of #19. Thank you for your time.

**Comment by zesterer** [comment]
Sorry this hasn't been fixed yet, Hopefully this will be fixed in the new year!
