### ISSUE TITLE
Remove redundant setters in the report builder.

### ISSUE THREAD

**Issue by Aurora2500** [zesterer/ariadne#32]
The `ReportBuilder` type has a bunch of duplicate setter functions that call their counterpart (`set_message` and `with_message`, `set_note` and `with_note`, etc).

It might be a good idea to remove these redundant setters as they needlessly complicate the interface of this type.

**Comment by zesterer** [comment]
I disagree that the functions are redundant. Creating a report inline and modifying an existing report are two conceptually distinct operations.

**Comment by abiriadev** [comment]
`set_xxx()` methods are quite useful for inline mutation of the builder, particularly within loops.
```rs
let mut report_builder = Report::build(...);

for my_error in errors {
	report_builder.add_label(Label::new(...));
}

report_builder.finish();
```

**Comment by zesterer** [comment]
Yep, they're two different use-cases. I'll close this now.
