### ISSUE TITLE
Ascii three dot (`⋮`) are not inline with other vertical lines.

### ISSUE THREAD

**Issue by HKalbasi** [zesterer/ariadne#43]
Sorry if duplicate. I mean this:
![image](https://user-images.githubusercontent.com/45197576/185762384-e52a9101-39d1-419a-bcde-ae11ab9dd09c.png)
Is it just my font? I'm using vscode terminal.

**Comment by zesterer** [comment]
Unfortunately, this is a font issue so there's not much I can do within Ariadne to fix this.

With Iosevka Fixed Slab, I see the following:
![image](https://user-images.githubusercontent.com/3268430/185805540-3526fdaf-8eec-40a1-bcb5-601de2507374.png)

**Comment by HKalbasi** [comment]
It doesn't work with my jupyter's font either, this time it is on the left:
![image](https://user-images.githubusercontent.com/45197576/185806441-d7290387-8f1e-4837-a21e-ad1091387d1f.png)
And the rest of characters are ok in both fonts, so maybe this only works by coincidence on your font? If it is not and it works in other fonts as well, feel free to close this.

**Comment by zesterer** [comment]
If you can find a similar Unicode character that behaves correctly, I'm happy to look into substituting it. Alternatively, there's the ASCII-only diagnostic rendering mode which might be more generally portable.

**Comment by HKalbasi** [comment]
`⸽` is working for me, though it is too close to the up and down lines. Ascii colon `:` is also ok. Strangely, every other character in this class changes the spaces width before that character in my font.

**Comment by zesterer** [comment]
![image](https://user-images.githubusercontent.com/3268430/185807713-2fad69c3-dbf1-4d83-9cbe-d4124611fb97.png)

![image](https://user-images.githubusercontent.com/3268430/185807736-28eccf17-045c-4e7f-b9fe-ec312e5f5eef.png)

I think the ASCII-only mode uses `:`, so hopefully this behaves a bit better. That said, removing the box characters tool in favour of ASCII is probably not a good long-term solution. It's frustrating that fonts have such inconsistent behaviour...

If you know of / can think of a better solution to this I'm happy to have a go at implementing it.

**Comment by nerdypepper** [comment]
i would suggest using characters from the box-drawing character class for this purpose, as fonts typically require those characters to line up perfectly, in this case, i would suggest `┆` (U+2506, light triple-dash vertical), or its siblings, `┊` and `╎` (quadruple and double-dash vertical).

**Comment by zesterer** [comment]
This is a good idea. I've made this change in 93f959c.

![image](https://user-images.githubusercontent.com/3268430/212353691-240a5acc-5290-4eaf-a000-3e5620003a40.png)
