### ISSUE TITLE
Report without source

### ISSUE THREAD

**Issue by oovm** [zesterer/ariadne#50]
I have encountered some IO errors that the file cannot be found. 

Since the file cannot be found, there is no source. 

How to print in this case?

**Comment by zesterer** [comment]
Do you have a small code example of the problem?

**Comment by ISSOtm** [comment]
I've [worked around this](https://github.com/ISSOtm/rsgbds/blob/4cd81e2920b71b335f4be744adcc3f307bdd5fd7/src/common/diagnostics.rs#L12-L57). It's not great, but it works.

**Comment by oovm** [comment]
Okay, this method is feasible.
