### ISSUE TITLE
Labels without messages still create extra vertical space

### ISSUE THREAD

**Issue by kaikalii** [zesterer/ariadne#51]
Consider this example:
```rust
use ariadne::*;

const TEXT: &str = "a b c d";

fn report_n_labels(n: usize) {
    let mut report = Report::build(ReportKind::Error, (), 0);
    for i in 0..n {
        report = report.with_label(Label::new(i * 2..i * 2 + 1));
    }
    report.finish().print(Source::from(TEXT)).unwrap();
}

fn main() {
    for n in 1..=4 {
        report_n_labels(n);
    }
}
```

This gives output:
```
Error: 
   ╭─[<unknown>:1:1]
   │
 1 │ a b c d
   · ─
   ·
───╯
Error:
   ╭─[<unknown>:1:1]
   │
 1 │ a b c d
   · ─ ─
   ·
   ·
   ·
───╯
Error:
   ╭─[<unknown>:1:1]
   │
 1 │ a b c d
   · ─ ─ ─
   ·
   ·
   ·
   ·
   ·
───╯
Error:
   ╭─[<unknown>:1:1]
   │
 1 │ a b c d
   · ─ ─ ─ ─
   ·
   ·
   ·
   ·
   ·
   ·
   ·
───╯
```

It looks like labels add extra vertical space for their messages even if they don't have messages.
This occurs with compact mode too.
I think this is undesirable.

**Comment by zesterer** [comment]
Yes, this is undesirable. I'll make sure to fix this for the refactor.

**Comment by Override-6** [comment]
I think i've fixed it in my [fork](https://github.com/Override-6/ariadne)
![image](https://github.com/zesterer/ariadne/assets/67809972/bc6007f2-70dc-44d1-87a3-3392ea7d9a70)
![image](https://github.com/zesterer/ariadne/assets/67809972/48906149-4d5c-4746-84a5-c3f515e34ba2)
