### ISSUE TITLE
Breaking change in 0.1.6 compared to 0.1.5

### ISSUE THREAD

**Issue by knutwalker** [zesterer/ariadne#69]
With https://github.com/zesterer/ariadne/pull/44 the public type `Report` got a new generic lifetime parameter, which is breaking in cases where the lifetime cannot be inferred or the `elided_lifetimes_in_paths` lint is denied.

In my understanding under cargo semver, this should be released as 0.2.0 instead.

**Comment by knutwalker** [comment]
See https://github.com/01mf02/jaq/issues/63 as an example of breaking change

**Comment by zesterer** [comment]
You're right, my apologies. I'll yank the release.

**Comment by zesterer** [comment]
Yanked, and `2.0.0` released in its place.

**Comment by 01mf02** [comment]
Are you sure that you really want to release this as 2.0 instead of 0.2?

**Comment by zesterer** [comment]
You make a good point, I'm half asleep today: `0.x` released are permitted to be breaking. Gah. Let's try that again :upside_down_face:

**Comment by zesterer** [comment]
Re-released as `0.2`.
