### ISSUE TITLE
convert `ariadne::Report` to `String`

### ISSUE THREAD

**Issue by LuckyTurtleDev** [zesterer/ariadne#94]
I would like to make parse errors available over an admin api, so I need to convert `ariadne::Report` to `String`.
But I see only a `print()` and `eprint()` function. How can I convert it to `String`?
Is their any reason why `ariadne::Report` do not impl the `std::fmt::Display` trait?

**Comment by zesterer** [comment]
Check out [`Report::write`](https://docs.rs/ariadne/latest/ariadne/struct.Report.html#method.write), it should do what you want. You can do:

```rs
let mut s = String::new();
my_report.write(cache, &mut s).unwrap();
```

**Comment by LuckyTurtleDev** [comment]
Thanks for the fast answer. Looks like I have oversee the `write` function.
Sadly `String` does not impl `Write`. I have use an `Vec<u8>` instead and convert it back to string:
```rust
let mut output = Vec::<u8>::new();
report
.write((path_str, Source::from(buf)),&mut output)
.unwrap();
String::from_utf8_lossy(&output).into_owned()

**Comment by zesterer** [comment]
Ah, yes, my bad. Unfortunately Ariadne currently requires a byte-like buffer. Hopefully this will change in the future.
